# Copyright 2018 Google LLC.
# SPDX-License-Identifier: Apache-2.0


build_task:
  name: Bazel build and test
  container:
    image: cirrusci/bazel:latest
  build_packages_script:
    bazel build --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST  //packages/...

steps:
- restore_cache:
  keys:
  - source-v1-{{ .Branch }}-{{ .Revision }}
  - source-v1-{{ .Branch }}-
  - source-v1-
- checkout
- save_cache:
  key: source-v1-{{ .Branch }}-{{ .Revision }}
  paths:
  - ".git"

